# Netlify configuration for React SPA with client-side routing
[build]
  # Specify the build command and output directory
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200